<a href="https://colab.research.google.com/github/aonekoda/Python_Sklearn/blob/master/Exercise/Exercise02_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제 02 NumPy, Pandas

### NumPy 실습 문제

### 문제 1.

길이가 10인 0-벡터(모든 요소가 0인)를 만드세요.



In [14]:
import numpy as np

x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 문제 2.

길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.



In [15]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

문제 3.

10 부터 49까지의 값을 가지는 벡터를 만드세요.



In [16]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

문제 4.

위 벡터의 순서를 바꾸세요.



In [17]:
x = np.arange(50, 9, -1)
x

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

문제 5.

0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.



In [18]:
x = np.reshape(np.arange(9), (3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

문제 6.

벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.



In [19]:
x = np.array([1,2,0,0,4,0])

x[x != 0]

array([1, 2, 4])

문제 7.

3x3 단위 행렬(identity matrix, 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인)을 만드세요



In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

문제 8.

난수 원소를 가지는 3x3 행렬을 만드세요



In [21]:
x = np.random.rand(3,3)
x

array([[0.34621317, 0.97679636, 0.66483016],
       [0.0484466 , 0.45817415, 0.30574321],
       [0.51163369, 0.12161302, 0.2142399 ]])

문제 9.

위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.



In [22]:
print(x.min(), x.max())


0.048446597218644305 0.9767963595218836


문제 10.

위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [23]:
print(np.mean(x, axis = 1)) # 행평균
print(np.mean(x, axis = 0)) # 열평균

[0.66261323 0.27078799 0.28249554]
[0.30209782 0.51886118 0.39493776]


# Pandas 실습문제

다음의 코드를 실행하여 샘플 데이터를 생성하시오.

seaborn 패키지에 있는 타이타닉 데이터를 사용하여 실습한다. 필요한 데이터를 로드한다.

In [24]:
import pandas as pd

titanic = pd.read_csv("../data/titanic.csv")

titanic.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

문제 1. 

타이타닉호 승객중 성별(sex) 인원수, 나이별(age) 인원수, 선실별(class) 인원수, 사망/생존(alive) 인원수를 구하라. (힌트. value_counts 메소드)

In [25]:
# 성별 인원수
titanic['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [26]:
# 나이별 인원수
titanic['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

In [27]:
# 선실별 인원수
titanic['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [28]:
# 사망/생존(alive) 인원수
titanic['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

문제 2.

성별(sex) 및 선실(class)에 의한 생존율을 피봇 데이터 형태로 만들어 표시하시오.(힌트. pivot_table)

In [29]:
titanic.pivot_table('Survived','Sex','Pclass')

Pclass         1         2         3
Sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

문제 3. 

'age' 컬럼의 null 값을 'age'의 median 값으로 대체하시오.(fillna 사용)

In [30]:
titanic['Age'].isnull().sum() # null값의 갯수


177

In [31]:
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].median())
titanic['Age'].isnull().sum()

0

문제 4.

가장 고액의 운임(fare)를 지불한 승객에 대한 정보를 출력하시오.

In [32]:
titanic['Fare'].max()

512.3292

In [33]:
titanic[titanic['Fare'] == titanic['Fare'].max() ]

PassengerId  Survived  Pclass  ...      Fare        Cabin  Embarked
258          259         1       1  ...  512.3292          NaN         C
679          680         1       1  ...  512.3292  B51 B53 B55         C
737          738         1       1  ...  512.3292         B101         C

[3 rows x 12 columns]

문제 5.

승객의 나이('age')의 평균을 구하시오.

In [34]:
titanic['Age'].mean()

29.36158249158249

문제 6. 

'embark_town' 이 'Queenstown' 이면서 생존한 남성 승객에 대한 정보를 출력하시오.

In [35]:
titanic[(titanic['Embarked'] == 'Q') & (titanic['Survived']==1) & (titanic['Sex']=='male')]

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
301          302         1       3  ...  23.25   NaN         Q
510          511         1       3  ...   7.75   NaN         Q
828          829         1       3  ...   7.75   NaN         Q

[3 rows x 12 columns]