<a href="https://colab.research.google.com/github/aonekoda/Python_Sklearn/blob/master/Exercise/Exercise02_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제 02 NumPy, Pandas

### NumPy 실습 문제

### 문제 1.

길이가 10인 0-벡터(모든 요소가 0인)를 만드세요.



In [0]:
import numpy as np

x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 문제 2.

길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.



In [0]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

문제 3.

10 부터 49까지의 값을 가지는 벡터를 만드세요.



In [0]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

문제 4.

위 벡터의 순서를 바꾸세요.



In [0]:
x = np.arange(50, 9, -1)
x

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

문제 5.

0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.



In [0]:
x = np.reshape(np.arange(9), (3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

문제 6.

벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.



In [0]:
x = np.array([1,2,0,0,4,0])

x[x != 0]

array([1, 2, 4])

문제 7.

3x3 단위 행렬(identity matrix, 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인)을 만드세요



In [0]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

문제 8.

난수 원소를 가지는 3x3 행렬을 만드세요



In [0]:
x = np.random.rand(3,3)
x

array([[0.8771233 , 0.68406461, 0.10370328],
       [0.52491309, 0.26958875, 0.40917833],
       [0.92413286, 0.96408335, 0.63254064]])

문제 9.

위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.



In [0]:
print(x.min(), x.max())


0.10370328457043121 0.964083350492204


문제 10.

위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [0]:
print(np.mean(x, axis = 1)) # 행평균
print(np.mean(x, axis = 0)) # 열평균

[0.55496373 0.40122672 0.84025228]
[0.77538975 0.63924557 0.38180742]


# Pandas 실습문제

다음의 코드를 실행하여 샘플 데이터를 생성하시오.

seaborn 패키지에 있는 타이타닉 데이터를 사용하여 실습한다. 필요한 데이터를 로드한다.

In [0]:
import seaborn as sns
titanic = sns.load_dataset("titanic")

titanic.head()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

문제 1. 

타이타닉호 승객중 성별(sex) 인원수, 나이별(age) 인원수, 선실별(class) 인원수, 사망/생존(alive) 인원수를 구하라. (힌트. value_counts 메소드)

In [0]:
# 성별 인원수
titanic['sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [0]:
# 나이별 인원수
titanic['age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: age, Length: 88, dtype: int64

In [0]:
# 선실별 인원수
titanic['class'].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [0]:
# 사망/생존(alive) 인원수
titanic['alive'].value_counts()

no     549
yes    342
Name: alive, dtype: int64

문제 2.

성별(sex) 및 선실(class)에 의한 생존율을 피봇 데이터 형태로 만들어 표시하시오.(힌트. pivot_table)

In [0]:
titanic.pivot_table('survived','sex','class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

문제 3. 

'age' 컬럼의 null 값을 'age'의 median 값으로 대체하시오.(fillna 사용)

In [0]:
titanic['age'].isnull().sum() # null값의 갯수


177

In [0]:
titanic['age'] = titanic['age'].fillna(titanic['age'].median())
titanic['age'].isnull().sum()

0

문제 4.

가장 고액의 운임(fare)를 지불한 승객에 대한 정보를 출력하시오.

In [0]:
titanic['fare'].max()

512.3292

In [0]:
titanic[titanic['fare'] == titanic['fare'].max() ]

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
258         1       1  female  35.0  ...   NaN    Cherbourg    yes   True
679         1       1    male  36.0  ...     B    Cherbourg    yes  False
737         1       1    male  35.0  ...     B    Cherbourg    yes   True

[3 rows x 15 columns]

문제 5.

승객의 나이('age')의 평균을 구하시오.

In [0]:
titanic['age'].mean()

29.36158249158249

문제 6. 

'embark_town' 이 'Queenstown' 이면서 생존한 남성 승객에 대한 정보를 출력하시오.

In [0]:
titanic[(titanic['embark_town'] == 'Queenstown') & (titanic['alive']=='yes') & (titanic['sex']=='male')]

survived  pclass   sex   age  ...  deck  embark_town  alive  alone
301         1       3  male  28.0  ...   NaN   Queenstown    yes  False
510         1       3  male  29.0  ...   NaN   Queenstown    yes   True
828         1       3  male  28.0  ...   NaN   Queenstown    yes   True

[3 rows x 15 columns]